DROP TABLE IF EXISTS `reservations_db`.`RESERVATIONS`;

CREATE TABLE `reservations_db`.`RESERVATIONS` (
  `RESERVATION_ID` INT(4) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `RESERVATION_GUEST_ID` INT(4) UNSIGNED ZEROFILL NOT NULL,
  `RESERVATION_USER_ID` INT(4) UNSIGNED ZEROFILL NOT NULL,
  `RESERVATION_CABIN_ID` INT(4) UNSIGNED ZEROFILL NOT NULL,
  `RESERVATION_ARRIVAL_DATE` DATE NOT NULL,
  `RESERVATION_DEPARTURE_DATE` DATE NOT NULL,
  `RESERVATION_STATE` ENUM('CONFIRMED', 'CANCELED', 'ON_HOLD') NOT NULL,
  `RESERVATION_GUEST_EMAIL` VARCHAR(255) NOT NULL,
  `RESERVATION_GUEST_ADDRESS` VARCHAR(255) NOT NULL,
  `RESERVATION_QUANTITY` INT(1) NOT NULL,
  `RESERVATION_DETAILS` TEXT CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`RESERVATION_ID`),
  INDEX `fk_RESERVATION_USER_ID_idx` (`RESERVATION_USER_ID` ASC),
  INDEX `fk_RESERVATIONS_GUEST_ID_idx` (`RESERVATION_GUEST_ID` ASC),
  INDEX `fk_RESERVATION_CABIN_ID_idx` (`RESERVATION_CABIN_ID` ASC),
  CONSTRAINT `fk_RESERVATION_USER_ID`
    FOREIGN KEY (`RESERVATION_USER_ID`)
    REFERENCES `reservations_db`.`USERS` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RESERVATION_GUEST_ID`
    FOREIGN KEY (`RESERVATION_GUEST_ID`)
    REFERENCES `reservations_db`.`USERS` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RESERVATION_CABIN_ID`
    FOREIGN KEY (`RESERVATION_CABIN_ID`)
    REFERENCES `reservations_db`.`CABINS` (`CABIN_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
