DROP TABLE IF EXISTS `reservations_db`.`IMAGES`;

CREATE TABLE `reservations_db`.`IMAGES` (
  `IMAGE_ID` INT(4) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `CABIN_ID` INT(4) UNSIGNED ZEROFILL NOT NULL,
  `IMAGE_PATH` VARCHAR(255) NOT NULL,
  `IMAGE_ALTERNATE_TEXT` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`IMAGE_ID`),
  INDEX `fk_CABIN_ID_idx` (`CABIN_ID` ASC),
  CONSTRAINT `fk_CABIN_ID`
    FOREIGN KEY (`CABIN_ID`)
    REFERENCES `reservations_db`.`CABINS` (`CABIN_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
