DROP TABLE IF EXISTS `reservations_db`.`THUMBNAILS`;

CREATE TABLE `reservations_db`.`THUMBNAILS` (
  `THUMBNAIL_ID` INT(4) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `CABIN_ID` INT(4) UNSIGNED ZEROFILL NOT NULL,
  `THUMBNAIL_PATH` VARCHAR(255) NULL,
  `THUMBNAIL_ALTERNATE_TEXT` VARCHAR(20) NULL,
  PRIMARY KEY (`THUMBNAIL_ID`),
  INDEX `fk_THUMBNAILS_CABIN_ID_idx` (`CABIN_ID` ASC),
  CONSTRAINT `fk_THUMBNAILS_CABIN_ID`
    FOREIGN KEY (`CABIN_ID`)
    REFERENCES `reservations_db`.`CABINS` (`CABIN_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);
