DROP TABLE IF EXISTS `reservations_db`.`CABINS`;

CREATE TABLE `reservations_db`.`CABINS` (
  `CABIN_ID` INT(4) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `CABIN_NAME` VARCHAR(45) CHARACTER SET 'latin1' NOT NULL,
  `CABIN_DESCRIPTION` VARCHAR(45) CHARACTER SET 'latin1' NOT NULL,
  `CABIN_MAX_OCCUPANCY` INT(1) NOT NULL,
  PRIMARY KEY (`CABIN_ID`));
